export const DEMO_SCENARIOS = [
  {
    id: "boundary-drift",
    label: "Boundary drift",
    shortLabel: "Excavation · Verify",
    mode: "excavation",
    location: "Northline demo corridor",
    time: "10:42 AM",
    status: "VERIFY",
    statusTone: "verify",
    headline: "Activity moved beyond the marked ticket area.",
    summary:
      "Thistle detected a second excavation signature just outside the active 811 work zone. The ticket is real, but it does not support this location.",
    ticket: {
      id: "811-240184",
      status: "ACTIVE",
      scope: "Service replacement between MH-12 and 18 Cedar Way",
      window: "Jul 20 · 7:00 AM–5:00 PM",
      polygon: "248,126 596,126 596,338 248,338",
      center: [422, 232],
    },
    alerts: [
      {
        id: "TH-041",
        title: "Expected excavation",
        time: "10:18 AM",
        sensor: "T-03",
        x: 448,
        y: 224,
        priority: "LOW",
        action: "MONITOR",
        detail: "Vibration and equipment movement are inside the active ticket zone.",
        comparisons: [
          ["Ticket", "Active"],
          ["Location", "Inside zone"],
          ["Timing", "Expected"],
        ],
        reasons: [
          "Detection falls within the designated ticket boundary.",
          "Activity occurs during the authorized work window.",
          "No conflicting field signal is present.",
        ],
      },
      {
        id: "TH-044",
        title: "Excavation outside scope",
        time: "10:42 AM",
        sensor: "T-04",
        x: 646,
        y: 250,
        priority: "HIGH",
        action: "VERIFY BEFORE PROCEEDING",
        detail: "A new excavation signature appears east of the approved work boundary.",
        comparisons: [
          ["Ticket", "Nearby"],
          ["Location", "Outside zone"],
          ["Timing", "Active window"],
        ],
        reasons: [
          "A valid ticket makes the activity look supported at first glance.",
          "The new detection sits outside the ticket polygon.",
          "The nearby gas main increases the cost of assuming the scope is unchanged.",
        ],
      },
    ],
    selectedAlertId: "TH-044",
    assets: [
      { id: "GAS-4", label: "Gas main", kind: "gas", path: "M70 286 C240 272 380 290 760 274" },
      { id: "WTR-2", label: "Water", kind: "water", path: "M88 194 C250 208 510 188 758 202" },
      { id: "TEL-7", label: "Telecom", kind: "telecom", path: "M100 350 C300 322 560 350 748 330" },
    ],
    sensors: [
      { id: "T-03", x: 438, y: 188 },
      { id: "T-04", x: 664, y: 214 },
      { id: "T-05", x: 714, y: 316 },
    ],
    sequence: [
      ["09:52", "811 context received", "Ticket 811-240184 establishes the expected work area."],
      ["10:18", "Thistle alert TH-041", "Activity aligns with the ticket and stays low priority."],
      ["10:42", "Thistle alert TH-044", "A second detection appears beyond the approved boundary."],
      ["Now", "Riskseer interpretation", "Verify the changed work location before proceeding."],
    ],
  },
  {
    id: "aligned-work",
    label: "Expected work",
    shortLabel: "Excavation · Monitor",
    mode: "excavation",
    location: "Northline demo corridor",
    time: "9:24 AM",
    status: "MONITOR",
    statusTone: "monitor",
    headline: "The field signal matches the active work context.",
    summary:
      "Thistle detected excavation inside the designated 811 zone during the scheduled work window. Riskseer keeps it visible without creating an unnecessary interruption.",
    ticket: {
      id: "811-240219",
      status: "ACTIVE",
      scope: "Hand excavation and service connection at Parcel 14",
      window: "Jul 20 · 8:00 AM–3:00 PM",
      polygon: "304,132 592,132 592,330 304,330",
      center: [448, 231],
    },
    alerts: [
      {
        id: "TH-052",
        title: "Expected excavation",
        time: "9:24 AM",
        sensor: "T-03",
        x: 458,
        y: 242,
        priority: "LOW",
        action: "MONITOR",
        detail: "The detected activity is consistent with the ticketed work area and schedule.",
        comparisons: [
          ["Ticket", "Active"],
          ["Location", "Inside zone"],
          ["Timing", "Expected"],
        ],
        reasons: [
          "The detection is centered inside the designated work zone.",
          "The ticket scope includes the observed work type.",
          "The system records the activity without asking the operator to interrupt it.",
        ],
      },
    ],
    selectedAlertId: "TH-052",
    assets: [
      { id: "GAS-4", label: "Gas main", kind: "gas", path: "M70 286 C240 272 380 290 760 274" },
      { id: "WTR-2", label: "Water", kind: "water", path: "M88 194 C250 208 510 188 758 202" },
      { id: "TEL-7", label: "Telecom", kind: "telecom", path: "M100 350 C300 322 560 350 748 330" },
    ],
    sensors: [
      { id: "T-02", x: 326, y: 186 },
      { id: "T-03", x: 472, y: 204 },
      { id: "T-04", x: 620, y: 236 },
    ],
    sequence: [
      ["08:06", "811 context received", "Ticket 811-240219 establishes the work area and schedule."],
      ["09:24", "Thistle alert TH-052", "Excavation activity is detected inside the designated zone."],
      ["Now", "Riskseer interpretation", "Monitor the aligned activity without interrupting the crew."],
    ],
  },
  {
    id: "temporary-security",
    label: "After-hours access",
    shortLabel: "Temporary security · Review",
    mode: "security",
    location: "Cedar staging yard",
    time: "11:36 PM",
    status: "REVIEW NOW",
    statusTone: "review",
    headline: "Movement crossed a temporary boundary after the site closed.",
    summary:
      "Thistle detected a vehicle entering the material yard outside the authorized delivery window. Riskseer separates it from earlier expected movement and asks for a human check.",
    ticket: {
      id: "SITE-07",
      status: "ARMED",
      scope: "Temporary material and equipment staging perimeter",
      window: "Authorized access · 6:00 AM–7:00 PM",
      polygon: "210,104 654,104 690,348 182,348",
      center: [436, 226],
    },
    alerts: [
      {
        id: "TH-071",
        title: "Scheduled delivery",
        time: "4:18 PM",
        sensor: "T-11",
        x: 250,
        y: 230,
        priority: "LOW",
        action: "LOGGED",
        detail: "Vehicle movement matches the authorized delivery window and entry point.",
        comparisons: [
          ["Access", "Authorized"],
          ["Location", "Entry gate"],
          ["Timing", "Expected"],
        ],
        reasons: [
          "The vehicle entered through the designated access point.",
          "Movement occurred during the delivery window.",
          "The event remains visible but does not require escalation.",
        ],
      },
      {
        id: "TH-078",
        title: "After-hours vehicle",
        time: "11:36 PM",
        sensor: "T-14",
        x: 604,
        y: 286,
        priority: "HIGH",
        action: "HUMAN REVIEW",
        detail: "Vehicle-scale movement crossed the east perimeter after authorized access ended.",
        comparisons: [
          ["Access", "Unconfirmed"],
          ["Location", "East perimeter"],
          ["Timing", "After hours"],
        ],
        reasons: [
          "The movement does not use the designated entry point.",
          "The authorized access window ended more than four hours earlier.",
          "The alert is prioritized for review; Riskseer does not identify a person or make an enforcement decision.",
        ],
      },
    ],
    selectedAlertId: "TH-078",
    assets: [],
    sensors: [
      { id: "T-11", x: 236, y: 186 },
      { id: "T-12", x: 426, y: 124 },
      { id: "T-13", x: 656, y: 194 },
      { id: "T-14", x: 628, y: 304 },
    ],
    sequence: [
      ["16:18", "Thistle alert TH-071", "A scheduled delivery enters through the west gate."],
      ["19:00", "Access window closes", "The temporary site moves into after-hours monitoring."],
      ["23:36", "Thistle alert TH-078", "Vehicle-scale movement crosses the east perimeter."],
      ["Now", "Riskseer interpretation", "Request a human review of the after-hours movement."],
    ],
  },
];
