export const DEMO_SCENARIOS = [
  {
    id: "boundary-drift",
    label: "Boundary drift",
    shortLabel: "Excavation · Verify",
    mode: "excavation",
    location: "Northline demo corridor",
    time: "10:42 AM",
    status: "VERIFY",
    statusTone: "verify",
    headline: "Activity moved beyond the marked ticket area.",
    summary:
      "Thistle detected a second excavation signature just outside the active 811 work zone. The ticket is real, but it does not support this location.",
    ticket: {
      id: "811-240184",
      status: "ACTIVE",
      scope: "Service replacement between MH-12 and 18 Cedar Way",
      window: "Jul 20 · 7:00 AM–5:00 PM",
      polygon: "248,126 596,126 596,338 248,338",
      center: [422, 232],
    },
    alerts: [
      {
        id: "TH-041",
        title: "Expected excavation",
        time: "10:18 AM",
        sensor: "T-03",
        x: 448,
        y: 224,
        priority: "LOW",
        action: "MONITOR",
        detail: "Vibration and equipment movement are inside the active ticket zone.",
        comparisons: [
          ["Ticket", "Active"],
          ["Location", "Inside zone"],
          ["Timing", "Expected"],
        ],
        reasons: [
          "Detection falls within the designated ticket boundary.",
          "Activity occurs during the authorized work window.",
          "No conflicting field signal is present.",
        ],
      },
      {
        id: "TH-044",
        title: "Excavation outside scope",
        time: "10:42 AM",
        sensor: "T-04",
        x: 646,
        y: 250,
        priority: "HIGH",
        action: "VERIFY BEFORE PROCEEDING",
        detail: "A new excavation signature appears east of the approved work boundary.",
        comparisons: [
          ["Ticket", "Nearby"],
          ["Location", "Outside zone"],
          ["Timing", "Active window"],
        ],
        reasons: [
          "A valid ticket makes the activity look supported at first glance.",
          "The new detection sits outside the ticket polygon.",
          "The nearby gas main increases the cost of assuming the scope is unchanged.",
        ],
      },
    ],
    selectedAlertId: "TH-044",
    assets: [
      { id: "GAS-4", label: "Gas main", kind: "gas", path: "M70 286 C240 272 380 290 760 274" },
      { id: "WTR-2", label: "Water", kind: "water", path: "M88 194 C250 208 510 188 758 202" },
      { id: "TEL-7", label: "Telecom", kind: "telecom", path: "M100 350 C300 322 560 350 748 330" },
    ],
    sensors: [
      { id: "T-03", x: 438, y: 188 },
      { id: "T-04", x: 664, y: 214 },
      { id: "T-05", x: 714, y: 316 },
    ],
    sequence: [
      ["09:52", "811 context received", "Ticket 811-240184 establishes the expected work area."],
      ["10:18", "Thistle alert TH-041", "Activity aligns with the ticket and stays low priority."],
      ["10:42", "Thistle alert TH-044", "A second detection appears beyond the approved boundary."],
      ["Now", "Riskseer interpretation", "Verify the changed work location before proceeding."],
    ],
  },
  {
    id: "temporary-security",
    label: "Security trailer",
    shortLabel: "Temporary security · Confirm",
    mode: "security",
    location: "Cedar staging yard",
    time: "11:36 PM",
    status: "CONFIRM",
    statusTone: "review",
    headline: "The security trailer queued an event for confirmation.",
    summary:
      "A Thistle security trailer detected vehicle-scale movement near stored equipment after the site closed. Riskseer checks the schedule and monitored zone, then queues the event for an operator—not an algorithm—to confirm.",
    ticket: {
      id: "SEC-TRAILER-07",
      status: "ARMED",
      scope: "Temporary security trailer coverage for the equipment staging area",
      window: "Authorized access · 6:00 AM–7:00 PM",
      polygon: "210,104 654,104 676,344 196,344",
      center: [436, 224],
    },
    alerts: [
      {
        id: "TH-071",
        title: "Scheduled service visit",
        time: "5:42 PM",
        sensor: "Trailer camera 01",
        x: 338,
        y: 246,
        priority: "LOW",
        action: "LOGGED",
        detail: "A service vehicle entered through the gate during an authorized site window.",
        comparisons: [
          ["Schedule", "Matched"],
          ["Zone", "Trailer approach"],
          ["Timing", "Authorized"],
        ],
        reasons: [
          "The visit matches the temporary site access schedule.",
          "Movement follows the designated gate-to-trailer approach.",
          "Riskseer logs the event without adding it to the confirmation queue.",
        ],
      },
      {
        id: "TH-078",
        title: "After-hours trailer approach",
        time: "11:36 PM",
        sensor: "Trailer camera 02",
        x: 566,
        y: 256,
        priority: "HIGH",
        action: "QUEUE FOR CONFIRMATION",
        requiresConfirmation: true,
        detail: "Vehicle-scale movement entered the trailer confirmation zone after scheduled access ended.",
        comparisons: [
          ["Schedule", "No match"],
          ["Zone", "Trailer approach"],
          ["Timing", "After hours"],
        ],
        reasons: [
          "No authorized visit is scheduled for this time window.",
          "The detection occurs inside the security trailer's configured confirmation zone.",
          "Riskseer queues the event for a person to classify; it does not infer identity or intent.",
        ],
      },
    ],
    selectedAlertId: "TH-078",
    assets: [],
    sensors: [
      { id: "CAM-01", x: 398, y: 194 },
      { id: "CAM-02", x: 490, y: 194 },
      { id: "GATE", x: 222, y: 286 },
    ],
    sequence: [
      ["17:42", "Scheduled visit logged", "The trailer records expected service activity without queuing it."],
      ["19:00", "Site window closes", "The temporary security trailer moves into after-hours monitoring."],
      ["23:36", "Thistle event TH-078", "Vehicle-scale movement enters the trailer approach zone."],
      ["Now", "Confirmation queued", "An operator is asked to classify the event before the site response changes."],
    ],
  },
];
