export const DEMO_SCENARIOS = [
  {
    id: "boundary-drift",
    label: "Boundary drift",
    shortLabel: "Excavation · Verify",
    mode: "excavation",
    location: "Northline demo corridor",
    time: "10:42 AM",
    status: "VERIFY",
    statusTone: "verify",
    headline: "Activity moved beyond the marked ticket area.",
    summary:
      "Thistle detected a second excavation signature just outside the active 811 work zone. The ticket is real, but it does not support this location.",
    ticket: {
      id: "811-240184",
      status: "ACTIVE",
      scope: "Service replacement between MH-12 and 18 Cedar Way",
      window: "Jul 20 · 7:00 AM–5:00 PM",
      polygon: "248,126 596,126 596,338 248,338",
      center: [422, 232],
    },
    alerts: [
      {
        id: "TH-041",
        title: "Expected excavation",
        time: "10:18 AM",
        sensor: "T-03",
        x: 448,
        y: 224,
        priority: "LOW",
        action: "MONITOR",
        detail: "Vibration and equipment movement are inside the active ticket zone.",
        comparisons: [
          ["Ticket", "Active"],
          ["Location", "Inside zone"],
          ["Timing", "Expected"],
        ],
        reasons: [
          "Detection falls within the designated ticket boundary.",
          "Activity occurs during the authorized work window.",
          "No conflicting field signal is present.",
        ],
      },
      {
        id: "TH-044",
        title: "Excavation outside scope",
        time: "10:42 AM",
        sensor: "T-04",
        x: 646,
        y: 250,
        priority: "HIGH",
        action: "VERIFY BEFORE PROCEEDING",
        detail: "A new excavation signature appears east of the approved work boundary.",
        comparisons: [
          ["Ticket", "Nearby"],
          ["Location", "Outside zone"],
          ["Timing", "Active window"],
        ],
        reasons: [
          "A valid ticket makes the activity look supported at first glance.",
          "The new detection sits outside the ticket polygon.",
          "The nearby gas main increases the cost of assuming the scope is unchanged.",
        ],
      },
    ],
    selectedAlertId: "TH-044",
    assets: [
      { id: "GAS-4", label: "Gas main", kind: "gas", path: "M70 286 C240 272 380 290 760 274" },
      { id: "WTR-2", label: "Water", kind: "water", path: "M88 194 C250 208 510 188 758 202" },
      { id: "TEL-7", label: "Telecom", kind: "telecom", path: "M100 350 C300 322 560 350 748 330" },
    ],
    sensors: [
      { id: "T-03", x: 438, y: 188 },
      { id: "T-04", x: 664, y: 214 },
      { id: "T-05", x: 714, y: 316 },
    ],
    sequence: [
      ["09:52", "811 context received", "Ticket 811-240184 establishes the expected work area."],
      ["10:18", "Thistle alert TH-041", "Activity aligns with the ticket and stays low priority."],
      ["10:42", "Thistle alert TH-044", "A second detection appears beyond the approved boundary."],
      ["Now", "Riskseer interpretation", "Verify the changed work location before proceeding."],
    ],
  },
  {
    id: "temporary-security",
    label: "Camera cue",
    shortLabel: "Temporary security · Verify",
    mode: "security",
    location: "Cedar staging yard",
    time: "11:36 PM",
    status: "CONFIRM",
    statusTone: "review",
    headline: "Thistle cued an existing camera for verification.",
    summary:
      "A distributed Thistle node detected ground-coupled activity beyond the camera's normal attention area. Riskseer checks the site schedule, cues the mobile camera, and gives the resulting event to an operator to verify.",
    ticket: {
      id: "TEMP-SITE-07",
      status: "ARMED",
      scope: "Four Thistle cue nodes around the laydown yard, paired with one existing mobile camera trailer",
      window: "Authorized access · 6:00 AM–7:00 PM",
      polygon: "146,78 686,78 686,370 146,370",
      center: [416, 224],
    },
    alerts: [
      {
        id: "TH-071",
        title: "Scheduled service visit",
        time: "5:42 PM",
        sensor: "Thistle S-21",
        x: 246,
        y: 320,
        priority: "LOW",
        action: "LOGGED",
        detail: "A service vehicle entered through the gate during an authorized site window.",
        comparisons: [
          ["Schedule", "Matched"],
          ["Zone", "Gate approach"],
          ["Timing", "Authorized"],
        ],
        reasons: [
          "The visit matches the temporary site access schedule.",
          "Ground activity follows the designated gate approach.",
          "Riskseer logs the event without adding it to the confirmation queue.",
        ],
      },
      {
        id: "TH-078",
        title: "After-hours ground activity",
        time: "11:36 PM",
        sensor: "Thistle S-24",
        x: 610,
        y: 262,
        priority: "HIGH",
        action: "VERIFY CAMERA CUE",
        requiresConfirmation: true,
        verification: {
          source: "Thistle S-24",
          target: "Mobile camera PTZ-01",
          status: "Cue ready",
        },
        detail: "Ground-coupled activity was detected beside stored equipment after scheduled access ended.",
        comparisons: [
          ["Schedule", "No match"],
          ["Zone", "Laydown edge"],
          ["Timing", "After hours"],
        ],
        reasons: [
          "No authorized visit is scheduled for this time window.",
          "The nearest Thistle node cues the existing camera toward the event location.",
          "Riskseer asks a person to verify the camera view; it does not infer identity or intent.",
        ],
      },
    ],
    selectedAlertId: "TH-078",
    assets: [],
    sensors: [
      { id: "S-21", x: 160, y: 326 },
      { id: "S-22", x: 176, y: 126 },
      { id: "S-23", x: 638, y: 126 },
      { id: "S-24", x: 654, y: 326 },
    ],
    sequence: [
      ["17:42", "Expected activity logged", "Thistle S-21 records the scheduled service approach."],
      ["19:00", "Site window closes", "The distributed cue layer remains active around the temporary yard."],
      ["23:36", "Thistle event TH-078", "S-24 detects activity beside the equipment laydown area."],
      ["Now", "Camera cued", "PTZ-01 is directed toward the event and an operator is asked to verify it."],
    ],
  },
];
